// swift-tools-version: 6.1

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "RookieRush",
    defaultLocalization: "en",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "RookieRush",
            targets: ["AppModule"],
            bundleIdentifier: "com.rookierush.level1",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .gamepad),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "Sources/AppModule",
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ]
        )
    ]
)
